#include <iostream>
#include <stdexcept>
using namespace std;

int main() {
   int userNum;
   int divNum;
   int result;
   cin.exceptions(ios::failbit);       // Allow cin to throw exceptions

   /* Type your code here. */
   try{
   cin >> userNum;
   cin >>divNum;
   if(divNum==0)throw runtime_error("Devide by zero!");
   int x = userNum/divNum;
   cout<<x<<endl;
   }
   catch(ios_base::failure &e){
      cout<<"Input Exception: basic_ios::clear: iostream error"<<endl;
      cin.clear();}
   catch(runtime_error &e){
      cout<<"Runtime Exception:  Divide by zero!"<<endl;
      }
   
   return 0;
}
